server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://39.108.164.17:3306/kakarot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: kakarot
    password: A1411050104a*
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置盐值（加密解密密钥），我们配置在这里只是为了测试方便
# 生产环境中，切记不要这样直接进行设置，可通过环境变量、命令行等形式进行设置。下文会讲
jasypt:
  encryptor:
    password: 123456