server:
  port: 8888

web:
  upload-path: D:/content/
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: kakarot
    password: A1411050104a*
    url: jdbc:mysql://39.108.164.17:3306/kakarot?useUnique=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: HikariCP
      max-lifetime: 1800000
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*xml



